AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Timesheet OCR System - Basic deployment without S3 event

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024
    Runtime: python3.13

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev/staging/prod)

Resources:
  # Input S3 Bucket
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'timesheetocr-input-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # DynamoDB Table for Timesheet Data
  TimesheetTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'TimesheetOCR-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ResourceName
          AttributeType: S
        - AttributeName: DateProjectCode
          AttributeType: S
        - AttributeName: ProjectCodeGSI
          AttributeType: S
        - AttributeName: YearMonth
          AttributeType: S
      KeySchema:
        - AttributeName: ResourceName
          KeyType: HASH
        - AttributeName: DateProjectCode
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ProjectCodeIndex
          KeySchema:
            - AttributeName: ProjectCodeGSI
              KeyType: HASH
            - AttributeName: DateProjectCode
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: YearMonthIndex
          KeySchema:
            - AttributeName: YearMonth
              KeyType: HASH
            - AttributeName: ResourceName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: TimesheetOCR

  # Lambda Function (without S3 event - we'll invoke manually)
  OCRFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'TimesheetOCR-ocr-${Environment}'
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TimesheetTable
          MODEL_ID: 'anthropic.claude-3-haiku-20240307-v1:0'
          MAX_TOKENS: '4096'
          ENVIRONMENT: !Ref Environment
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref InputBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref TimesheetTable
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource:
                - !Sub 'arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-haiku-20240307-v1:0'

Outputs:
  InputBucketName:
    Description: Input S3 bucket for timesheet images
    Value: !Ref InputBucket
  DynamoDBTableName:
    Description: DynamoDB table for timesheet data
    Value: !Ref TimesheetTable
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt OCRFunction.Arn
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref OCRFunction
